[build]
builder = "HEROKU"

[build.buildCommand]
command = "pip install flask redis requests gunicorn"

[deploy]
startCommand = "python rail_main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
