[build]
builder = "NIXPACKS"

[build.nixpacks]
aptPackages = ["redis-server"]

[variables]
PYTHONPATH = "/app"

[deploy]
startCommand = "python rail_main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
